---
- name: Start gluster
  ansible.builtin.service:
    name: "{{ glusterfs_daemon }}"
    state: started

- name: Restart gluster
  ansible.builtin.service:
    name: "{{ glusterfs_daemon }}"
    state: restarted
