---
# - name: Ensure dependencies are installed.
#   ansible.builtin.apt:
#     name:
#       - gnupg2
#       - apt-transport-https
#       - ca-certificates
#     state: present

# - name: Ensure repository pubkey for GlusterFS is present.
#   apt_key:
#     url: 'https://download.gluster.org/pub/gluster/glusterfs/{{ glusterfs_gpg_key_version }}/rsa.pub'
#     state: present
#   register: glusterfs_pub_key_added

# - name: Get the DEB architecture.
#   ansible.builtin.command: dpkg --print-architecture
#   changed_when: false
#   register: deb_architecture

# - name: Ensure debian repo is present.
#   apt_repository:
#     repo: "deb https://download.gluster.org/pub/gluster/glusterfs/{{ glusterfs_deb_version }}/Debian/\
#       {{ ansible_distribution_release }}/{{ deb_architecture.stdout }}/apt {{ ansible_distribution_release }} \
#       main"
#     state: present
#     filename: gluster
#   register: glusterfs_deb_source_added

# - name: Ensure GlusterFS will reinstall if the DEB source was just added.
#   ansible.builtin.apt:
#     name:
#       - glusterfs-server
#       - glusterfs-client
#     state: absent
#   when: glusterfs_deb_source_added.changed
#   tags: ['skip_ansible_lint']

# - name: Ensure GlusterFS is installed.
#   ansible.builtin.apt:
#     name:
#       - glusterfs-server
#       - glusterfs-client
#     state: present
#     default_release: "{{ glusterfs_default_release }}"

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - gnupg2
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    update_cache: true
    state: present

- name: Add ppa repo
  ansible.builtin.apt_repository:
    repo: ppa:gluster/glusterfs-{{ gluster_version }}
    filename: glusterfs
    state: present

- name: Install glusterfs
  ansible.builtin.apt:
    name:
      - glusterfs-client
      - glusterfs-server
    state: present

- name: Start and enable glusterfs
  ansible.builtin.service:
    name: "{{ glusterfs_daemon }}"
    state: started
    enabled: true

- name: Configure brick
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/glusterfs.yml
  with_items: "{{ gluster_bricks_list }}"
  loop_control:
    loop_var: brick
