---
# - name: Ensure dependencies are installed.
#   ansible.builtin.yum:
#     name: "centos-release-gluster{{ gluster_version }}"
#     state: present

- name: Install glusterfs
  ansible.builtin.yum:
    name:
      - glusterfs-server
      - glusterfs-client
    state: present

- name: Start and enable glusterfs
  ansible.builtin.service:
    name: "{{ glusterfs_daemon }}"
    state: started
    enabled: true

- name: Configure brick
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/glusterfs.yml
  with_items: "{{ gluster_bricks_list }}"
  loop_control:
    loop_var: brick
